%Magnetic field generated by DC coils: cur(B0)=mu0 J
%use magnetic vector
% All units are in the International System.
%writed by Wu M Y, 2020.02.24
%contact: ymwu@pku.edu.cn
clear;clc;close all;
%%

rs=0;rd=0.6;
zs=0;zd=2.5;
N_coils=4; % number of the coils
mr=100;
mz=400;
pre=1e-6;%Iteration Accuracy

mu0=4*pi*1e-7;
I_th(1:N_coils)=0;
j_th(1:N_coils)=0;
posi_coils(1:4,1:N_coils)=0; %1:4 r1,z1,r2,z2 (Coordinates of the lower-left and upper-right points)
Nrz_posi(1:4,1:N_coils)=0;
I_th=500*100;%A

%Here we use four identical and equally spaced coils, 
% each with a current of 500A*100 (100 turns).
%The locations of the individual coils are given below.
% coil 1
i_coil=1;
posi_coils(1,i_coil)=0.3;
posi_coils(2,i_coil)=0.5;
posi_coils(3,i_coil)=posi_coils(1,i_coil)+0.25;
posi_coils(4,i_coil)=posi_coils(2,i_coil)+0.15;

% coil 2
i_coil=2;
posi_coils(1,i_coil)=0.3;
posi_coils(2,i_coil)=0.5+0.45*1;
posi_coils(3,i_coil)=posi_coils(1,i_coil)+0.25;
posi_coils(4,i_coil)=posi_coils(2,i_coil)+0.15;

% coil 3
i_coil=3;
posi_coils(1,i_coil)=0.3;
posi_coils(2,i_coil)=0.5+0.45*2;
posi_coils(3,i_coil)=posi_coils(1,i_coil)+0.25;
posi_coils(4,i_coil)=posi_coils(2,i_coil)+0.15;

% coil 4
i_coil=4;
posi_coils(1,i_coil)=0.3;
posi_coils(2,i_coil)=0.5+0.45*3;
posi_coils(3,1:i_coil)=posi_coils(1,i_coil)+0.25;
posi_coils(4,i_coil)=posi_coils(2,i_coil)+0.15;

dr=(rd-rs)/(mr-1);
dz=(zd-zs)/(mz-1);
r(1:mr)=0;
z(1:mz)=0;
r=rs+((1:mr)-1)*dr;
z=zs+((1:mz)-1)*dz;

dz=dr;
dr2=dr*dr;
dz2=dz*dz;
d2r=2*dr;
d2z=2*dz;

itp=1;
Nrz_posi(itp,:)=floor((posi_coils(itp,:)-rs)/dr);
itp=3;
Nrz_posi(itp,:)=floor((posi_coils(itp,:)-rs)/dr);
itp=2;
Nrz_posi(itp,:)=floor((posi_coils(itp,:)-zs)/dz);
itp=4;
Nrz_posi(itp,:)=floor((posi_coils(itp,:)-zs)/dz);

j_th=I_th./((posi_coils(3,:)-posi_coils(1,:)).*(posi_coils(4,:)-posi_coils(2,:)));

B_c(1:mr,1:mz,1:3)=0;
jc(1:mr,1:mz)=0; 
A_th(1:mr,1:mz)=0;
A_old(1:mr,1:mz)=0;


for ic=1:N_coils
    ir1=Nrz_posi(1,ic);
    iz1=Nrz_posi(2,ic);
    ir2=Nrz_posi(3,ic);
    iz2=Nrz_posi(4,ic);

    jc(ir1:ir2,iz1:iz2)=j_th(ic);
end

%%
ite=0;
db=1;
while((ite<=50000) && (db>=pre))
    ite=ite+1;
    A_old=A_th;
    
    for k =2:mz-1
        for  i =2:mr-1
            tp1=2/dr2+2/dz2+1/(r(i)*r(i));
            tp2=mu0*jc(i,k);
            tp3=(A_th(i+1,k)+A_th(i-1,k))/dr2+(A_th(i,k+1)+A_th(i,k-1))/dz2;
            tp4=1/r(i)*(A_th(i+1,k)-A_th(i-1,k))/d2r;
            A_th(i,k)=(tp2+tp3+tp4)/tp1;
        end
    end
    
    i=1; A_th(i,2:mz-1)=2*A_th(i+1,2:mz-1)-A_th(i+2,2:mz-1);
    k=1; A_th(2:mr-1,k)=A_th(2:mr-1,k+1);
    
    i=mr; A_th(i,2:mz-1)=0;
    k=mz; A_th(2:mr-1,k)=A_th(2:mr-1,k-1);
    
    db=max(max(abs(A_old-A_th)));
    f_db(ite)=db;
end
Number_of_iterations=ite

for k =2:mz-1
    for  i =2:mr-1
        B_c(i,k,1)=-(A_th(i,k+1)-A_th(i,k-1))/d2z;
        B_c(i,k,3)=(A_th(i+1,k)-A_th(i-1,k))/d2r+A_th(i,k)/r(i);
    end
end
B_c(1,:,:)=B_c(2,:,:);
B_c(mr,:,:)=B_c(mr-1,:,:);
B_c(:,mz,:)=B_c(:,mz-1,:);
B_c(:,1,:)=B_c(:,2,:);

%%
close all;
ps = get(0, 'ScreenSize');
ls=20;  ls3=18;

ps3(1) = floor(ps(3)*0.1);
ps3(2) = floor(ps(4)*0.1);
ps3(3) = floor(ps(3)*0.9);
ps3(4) = floor(ps(4)*0.7);

ps2(1) = floor(ps(3)*0.1);
ps2(2) = floor(ps(4)*0.1);
ps2(3) = floor(ps(3)*0.5);
ps2(4) = floor(ps(4)*0.4);


ps(1) = floor(ps(3)*0.02);
ps(2) = floor(ps(4)*0.1);
ps(3) = floor(ps(3)*0.3);
ps(4) = floor(ps(4)*0.8);

plotstr=['ph.ZData=ph.CData;ipic=ipic+1;'...xlabel(''z'');ylabel(''r'');
    ,'colormap(''jet'');colorbar;shading interp;' ];

% figure %0
% semilogy(f_db)

pfg1=B_c(:,:,1);
pfg2=B_c(:,:,3);
pfg3=A_th(:,:);
pfg4=jc(:,:);
pfg5=sqrt(B_c(:,:,1).*B_c(:,:,1)+B_c(:,:,3).*B_c(:,:,3));
% pfg6=sqrt(B(:,:,1).*B(:,:,1)+B(:,:,3).*B(:,:,3));

figure %1
ipic=1;
subplot(2,2,ipic)
ph=pcolor(z,r,pfg1);
eval(plotstr);%execute the sentence in 'plotstr'
ylabel('r (m)');xlabel('z (m)');
title('B_r');
set(gca, 'fontsize', ls3); 
subplot(2,2,ipic)
ph=pcolor(z,r,pfg2);
eval(plotstr);%execute the sentence in 'plotstr'
ylabel('r (m)');xlabel('z (m)');
title('B_z');
set(gca, 'fontsize', ls3);
subplot(2,2,ipic)
ph=pcolor(z,r,pfg3);
eval(plotstr);%execute the sentence in 'plotstr'
ylabel('r (m)');xlabel('z (m)');
title('A_\theta');
set(gca, 'fontsize', ls3);
subplot(2,2,ipic)
ph=pcolor(z,r,pfg4);
eval(plotstr);%execute the sentence in 'plotstr'
ylabel('r (m)');xlabel('z (m)');
title('j_\theta');
set(gca, 'fontsize', ls3);
set(gcf,'position',ps3)
fname='B_A_J';
print([fname,'.png'],'-dpng');


figure %2
contour(z,r,pfg3,25);
ylabel('r (m)');xlabel('z (m)');
title('magnetic line');
set(gca, 'fontsize', ls3);    
set(gcf,'position',ps2)
fname='magnetic_line';
print([fname,'.png'],'-dpng');


figure %3
ipic=1;
subplot(3,1,ipic)
ph=pcolor(z,r,pfg1);
eval(plotstr);%execute the sentence in 'plotstr'
ylabel('r (m)');xlabel('z (m)');
title('B_r');
set(gca, 'fontsize', ls3); 
subplot(3,1,ipic)
ph=pcolor(z,r,pfg2);
eval(plotstr);%execute the sentence in 'plotstr'
ylabel('r');xlabel('z');
title('B_z');
set(gca, 'fontsize', ls3);
subplot(3,1,ipic)
ph=pcolor(z,r,pfg5);
eval(plotstr);%execute the sentence in 'plotstr'
ylabel('r (m)');xlabel('z (m)');
title('B_{total}');
set(gca, 'fontsize', ls3);
set(gcf,'position',ps)
fname='B';
print([fname,'.png'],'-dpng');


figure %4
plot(z,pfg5(1,:),'k-','LineWidth',1.5)
grid on;
xlim([0 max(z)]);
xlabel('z (m)');ylabel('B (T)');
set(gca, 'fontsize', ls3);    
set(gcf,'position',ps2)
fname='B_center';
print([fname,'.png'],'-dpng');
